# Generated by Django 2.2 on 2022-03-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_event', models.DateTimeField(auto_now_add=True)),
                ('object_detected', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Setting')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_event', models.DateField(auto_now_add=True)),
                ('type_of_threat', models.CharField(max_length=100)),
            ],
        ),
    ]
