# Generated by Django 2.2 on 2022-04-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='theme',
            field=models.BooleanField(default=True, verbose_name='theme'),
        ),
    ]
