# Generated by Django 2.2 on 2022-03-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_auto_20220317_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModelSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=100)),
                ('switch', models.BooleanField(default=True, verbose_name='switch')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardVideoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=100)),
                ('switch', models.BooleanField(default=True, verbose_name='switch')),
            ],
        ),
    ]
