# Generated by Django 2.2 on 2022-04-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_appearance_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(default='', max_length=100)),
                ('media', models.FileField(upload_to='recordings/')),
            ],
        ),
    ]
