# Generated by Django 2.2 on 2022-04-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_emailpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpreferences',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
